# Generated by Django 4.2.3 on 2023-07-31 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('created_on', models.DateField(auto_created=True)),
                ('uid', models.UUIDField(default=uuid.UUID('5e6b9ab4-d5fe-4f6c-a5a3-3abe71c254a5'), editable=False, primary_key=True, serialize=False)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('cheek', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
