# Generated by Django 4.2.3 on 2023-08-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onecult', '0003_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
