# Generated by Django 4.2.3 on 2023-08-10 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onecult', '0004_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a7db7545-3d51-460f-9c68-9d1effafb547'), editable=False, primary_key=True, serialize=False),
        ),
    ]
